sources:
  - name: portfolio_data
    schema: staging
    description: "Raw data ingested from DLT pipeline containing customers, loans, and location tables."
    tables:
      - name: customers
        description: "Raw customer-level information."
        meta:
          dagster:
            asset_key: ["dlt_source_customers"]

      - name: loans
        description: "Raw loan-level portfolio data."
        meta:
          dagster:
            asset_key: ["dlt_source_loans"]

      - name: location
        description: "Raw location and relationship manager data."
        meta:
          dagster:
            asset_key: ["dlt_source_locations"]
